### ISSUE TITLE
Restore Bluetooth state after reboot

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/sfos-onyx-issues#1]
Now needs one le scan at boot to get UI scan working.

**Comment by taaem** [comment]
Related commit https://github.com/mer-hybris/droid-config-onyx/commit/7e1b10cb0d6caf1767e6becb9129b0b02b6fd899

**Comment by kimmoli** [comment]
#8  and now it is always disabled after reboot

**Comment by kimmoli** [comment]
seems to get enabled after disabling flightmode, even if was disabled before.

**Comment by kimmoli** [comment]
https://github.com/mer-hybris/droid-config-onyx/pull/19
