### ISSUE TITLE
Support for dual-sim

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/sfos-onyx-issues#10]
ril_1 configs

**Comment by drgogeta86** [comment]
Just add  to /etc/ofono/ril_subscription.conf

```
[ril_1]
socket=/dev/socket/rild2
```

Regards

**Comment by kimmoli** [comment]
https://github.com/mlehtima/droid-config-fp2-sibon/blob/2.0.2/sparse/etc/ofono/ril_subscription.conf

**Comment by taaem** [comment]
And this https://github.com/mlehtima/droid-config-fp2-sibon/commit/0cb165d2579fef7e29ebd4fd808e05dd2a467952

**Comment by taaem** [comment]
Confirmed working https://twitter.com/nieldk/status/777564754546200576
