### ISSUE TITLE
Headset buttons

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/sfos-onyx-issues#11]
Now KEY_MEDIA does nothing, and other 2 buttons change volume (KEY_VOLUMEUP, KEY_VOLUMEDOWN)

kernel: Change KEY_MEDIA to BTN_0, KEY_VOLUMEUP to BTN_1 and KEY_VOLUMEDOWN to BTN_2 so can do something else with them...

noted that on sbj, BTN_0 seems to answer and hangup incoming call, but this is no happening on onyx oob

**Comment by kimmoli** [comment]
https://github.com/kimmoli/android_kernel_oneplus_msm8974/commit/fd9a1846597bbfe6cfd86d4090d89667fc830a71
https://github.com/kimmoli/buttonjackd

**Comment by taaem** [comment]
Maybe add this to obs and https://github.com/mer-hybris/droid-config-onyx/blob/master/patterns/jolla-hw-adaptation-onyx.yaml so its included in all new images

**Comment by kimmoli** [comment]
done
