### ISSUE TITLE
Video recording volume low

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/sfos-onyx-issues#12]
This is weird because on alpha1 or so the volume was almost too high, had to hold breath. Or was it with 4K hal ??

Nope, not 4K. It is also silent.

**Comment by kimmoli** [comment]
Difference is between alpha-2 and alpha-3. With alpha-2 the recording volume is HIGH

**Comment by kimmoli** [comment]
Not a kernel issue, alpha2 + latest kernel, still loud

**Comment by kimmoli** [comment]
https://pastebin.com/Z16NnfhF

**Comment by kimmoli** [comment]
alpha-2 uses pulseaudio-modules-droid-8.0.47-10.5.1.jolla.armv7hl
alpha-3 uses pulseaudio-modules-droid-8.0.47-10.2.1.jolla.armv7hl

```
Binary files alpha2/usr/lib/pulse-6.0/modules/libdroid-util.so and alpha3/usr/lib/pulse-6.0/modules/libdroid-util.so differ
Binary files alpha2/usr/lib/pulse-6.0/modules/module-policy-enforcement.so and alpha3/usr/lib/pulse-6.0/modules/module-policy-enforcement.so differ
```

Replacing these two files from alpha-2, and video recording volume is again loud

**Comment by taaem** [comment]
Why is apha-3 using an older version of pulseaudio-modules-droid? That looks wrong.
https://github.com/kimmoli/pulseaudio-modules-droid this is behinf upstream so maybe we should update that. Also your commit isn't in for users https://build.merproject.org/package/view_file/nemo:testing:hw:oneplus:onyx/pulseaudio-modules-droid/_service?expand=1 since that poins to upstream

**Comment by kimmoli** [comment]
I tested, 10.5.1 was originally built in obs (afaiu), and it has been later rebuild to 10.5.2 which also fails.
https://build.merproject.org/package/show/nemo:devel:hw:oneplus:onyx/pulseaudio-modules-droid this is 8.0.49 and has low volume too.
I need to find what gives me working version.

**Comment by kimmoli** [comment]
Rebased to 8.0.49 and applied ATOI, but video recording is still low volume
https://github.com/kimmoli/pulseaudio-modules-droid/commit/57e42e72bd4e3b72a1fad52a9b00c8a34295dbea
https://build.merproject.org/package/show/nemo:devel:hw:oneplus:onyx/pulseaudio-modules-droid

**Comment by kimmoli** [comment]
Seems that the original libdroid-util.so is built without DROID_AUDIO_HAL_ATOI_FIX as it contains string:

```
%s=%u;%s=%u
```

https://github.com/kimmoli/pulseaudio-modules-droid/blob/master/src/common/droid-util.c#L1863

The freshly built-one has 

```
%s=%d;%s=%u
```

**Comment by kimmoli** [comment]
yeah. reverted this
https://github.com/mer-hybris/droid-hal-onyx/commit/05e8bcd8b8f60440fa2f151f7e1c26ce2b25cc7d
uploaded  droid-hal-onyx-0.0.6-201605232034.armv7hl.rpm /  droid-hal-onyx-devel-0.0.6-201605232034.armv7hl.rpm 
and rebuilt https://build.merproject.org/package/show/nemo:devel:hw:oneplus:onyx/pulseaudio-modules-droid (now without atoi fix) in obs, and recording volume is loud again.

**Comment by kimmoli** [comment]
https://github.com/mer-hybris/droid-hal-onyx/pull/2

**Comment by rinigus** [comment]
I do wonder whether the low volume of the recorded video at 2.1.3.7 is related to the same issue. I didn't test whether released beta has the same issue or it's introduced in the latest build. Do you have video volume fine in the released beta?

**Comment by kimmoli** [comment]
2.1.0.11 (beta4) video recording volume is ok (loud)

**Comment by rinigus** [comment]
Thanks for checking! So, something is either messed up in my build or something changed upstream...
