### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/sfos-onyx-issues#21]
Remove (?)
- usb-moded-mass-storage-android-config
- usb-moded-diag-mode-android

**Comment by taaem** [comment]
I understand that diag mode is unnecessary but mass storage is broken is suppose?

**Comment by kimmoli** [comment]
Mass storage is broken. 
It will cause something to just loop, and notification-spam, until connect e.g. charger to the USB port.

**Comment by taaem** [comment]
Add this to beta-2?

**Comment by kimmoli** [comment]
need to pre-test maybe

**Comment by kimmoli** [comment]
I have those removed from my device. works ok. 
https://github.com/mer-hybris/droid-config-onyx/pull/13
