### ISSUE TITLE
FM-Radio has no audio before toggling on loudspeaker

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/sfos-onyx-issues#36]

**Comment by kimmoli** [comment]
https://git.merproject.org/kimmoli/pulseaudio-policy-enforcement/commit/6395adb0547fd8edcdcbb6f79244b6901b0c093b

**Comment by kimmoli** [comment]
https://bugs.merproject.org/show_bug.cgi?id=1725

**Comment by jusa** [comment]
https://git.merproject.org/mer-core/pulseaudio-policy-enforcement/merge_requests/8

and change module loading in your devices foo.pa config to be:

load-module module-policy-enforcement route_sources_first=true

**Comment by kimmoli** [comment]
Just building and then testing on device

**Comment by kimmoli** [comment]
Tested, works.

**Comment by kimmoli** [comment]
https://github.com/mer-hybris/droid-config-onyx/pull/26

**Comment by kimmoli** [comment]
tested in rc2. works.
