### ISSUE TITLE
Virtual keyboard layouts missing

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/sfos-onyx-issues#49]
beta-6

After running OTA update on top of cleanly flashed 2.1.0.11, there were only Englis and 2 chinese keyboard layouts.

    pkcon install jolla-keyboard-layouts-all

as workaround

**Comment by rinigus** [comment]
This got resolved with updated patterns.

**Comment by rinigus** [comment]
fixed with 2.1.4.14
