### ISSUE TITLE
LED notification not showing up

### ISSUE THREAD

**Issue by rinigus** [kimmoli/sfos-onyx-issues#51]
In 2.1.3.7, regression:

On new mail, LED is not used for notifications. It seems also that LED is responding to charging with some timeout.

**Comment by kimmoli** [comment]
mce probing is depracated. Use config file instead.

/etc/mce/60-onyx.ini
---------------------
    [LEDConfigHybris]

    # Choose Vanilla backend
    BackEnd=vanilla

    # Configure base directories for red/green/blue channels
    RedDirectory=/sys/class/leds/red
    GreenDirectory=/sys/class/leds/green
    BlueDirectory=/sys/class/leds/blue

------------------------------------

/usr/bin/droid/rgb-led-ramp-rate.sh
-----------------------------------
    #!/bin/bash
    
    echo 5 > /sys/class/leds/red/ramp_step_ms
    echo 5 > /sys/class/leds/green/ramp_step_ms
    echo 5 > /sys/class/leds/blue/ramp_step_ms

**Comment by rinigus** [comment]
@kimmoli , thanks for finding it! I will fix it tonight.

**Comment by rinigus** [comment]
fix applied and working: https://github.com/rinigus/droid-config-onyx/commit/6ed7671b848ab33cfcb707accdf69c0d8cf05e61 . I will start looking into the speakephone issue

**Comment by nfs22** [comment]
/etc/mce/60-onyx.ini didn't work for me 
using /etc/mce/60-onyx.conf instead helped

**Comment by rinigus** [comment]
@nfs22 : really odd, it surely works as ini over here. Let's see if you have issues when we release 2.1.4.14 with .ini used to configure it.

**Comment by kimmoli** [comment]
Per source, https://git.merproject.org/mer-core/mce/blob/master/builtin-gconf.c#L2033 , this should be .conf

But all examples here are .ini https://github.com/mer-hybris/mce-plugin-libhybris/tree/master/inifiles

but are inifiles read from /etc/mce/mce.d/? https://git.merproject.org/mer-core/mce/blob/master/mce-conf.c#L416
(Comment might be wrong, reads from /etc/mce/ ... MCE_CONF_DIR => CONFDIR := $(_SYSCONFDIR)/mce =>_SYSCONFDIR = /etc )

**Comment by kimmoli** [comment]
Per source, .ini is correct.

**Comment by spiiroin** [comment]
To clarify, in mce there are two kinds of configuration mechanisms:

"Static" configuration: Values do not change during runtime - read from "/etc/mce/*.ini".

"Dynamic" configuration: Values can be changed during runtime via D-Bus - have hard coded defaults in code, can be overridden in "/etc/mce/*.conf", and delta to defaults is stored in /var/lib/mce.

(And yes, the "Process config data from /etc/mce/mce.d/xxx.ini files" comment is incorrect.)
