### ISSUE TITLE
4G is not shown in mobile network settings (due ui/mw version conflict) 

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/sfos-onyx-issues#6]
Needs new UI from Jolla

**Comment by kimmoli** [comment]
If you change mobile network from 4G (blank) to 3G/2G from settings, you can't change back

Restore 4G with

`dbus-send --system --type=method_call --print-reply --dest=org.ofono /ril_0 org.ofono.RadioSettings.SetProperty string:TechnologyPreference variant:string:lte`

**Comment by taaem** [comment]
Its fixed on 2.0.2.51
